create DATABASE DESOL;

USE DESOL;

CREATE TABLE EMPLEADOS(

	ID_EMPLEADO INT PRIMARY KEY IDENTITY (1,1),
	NOMBRE VARCHAR (20),
	APELLIDO VARCHAR(20),
	SUELDO DECIMAL(19,2),
	ANTIGUEDAD INT
	)

ALTER TABLE EMPLEADOS ADD FECHA_INICIO DATE
ALTER TABLE EMPLEADOS ADD TELEFONO VARCHAR(20)
ALTER TABLE EMPLEADOS ADD CATEGORIA VARCHAR(20)

CREATE TABLE EMPRESAS(
	ID_EMPRESA INT PRIMARY KEY IDENTITY(1,1),
	ID_EMPLEADO INT  ,
	DESCRIPCION VARCHAR(59),
	FECHA_INICIO DATE,
	FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
	);



CREATE TABLE CUSTOM_WORCK_EMPLOYEE(
	ID_CUSTOM INT IDENTITY (1,1),
	ID_EMPRESA INT
	FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS(ID_EMPRESA) )

 


 --SELECT * FROM EMPLEADOS


 CREATE PROCEDURE SP_EMPLOYEE_WORK_IT
 AS
 DECLARE @ENTRADA AS VARCHAR(1)
 
	BEGIN
	   
	     IF( ISNUMERIC(@ENTRADA) > 1)
		 PRINT 'DEBE INGRESAR UNA LETRA DE LA A HASTA LA Z'
		 ELSE
		 SELECT TELEFONO=(CASE WHEN TELEFONO <> '' OR TELEFONO IS NOT NULL THEN TELEFONO ELSE 'NO TIENE' END),* 
		 FROM EMPLEADOS WHERE SUELDO BETWEEN 10000 AND 300000
		 AND FECHA_INICIO BETWEEN '20150101' AND '20181231'
	END



	--3)

	SELECT TOP 10(SUELDO) FROM EMPLEADOS
	WHERE CATEGORIA IN (SELECT * FROM EMPLEADOS WHERE CATEGORIA = 'MEDIA')
	ORDER BY SUELDO DESC;