create database holamundo;
use holamundo;

-- CREO UNA TABLA 
create table animales(
	id int,
	tipo varchar (255),
	estado varchar (255),

	primary key (id)	
	);
-- INSERTO VALORES A DICHA TABLA 
	INSERT INTO animales ( TIPO, estado ) VALUES ( 'PUERQUITO' , 'FELIZ');

	INSERT INTO animales ( TIPO, estado ) VALUES ( 'PERRO' , 'FELIZ');

	INSERT INTO animales ( TIPO, estado ) VALUES ( 'MAGICARP' , 'TRISTE');


	SELECT * FROM animales ;

-- SELECCIONO EL ID Y EL TIPO DE LA TABLA ANIMALES, UNICAMENTE DONDE LOS VALORES DE ID SEAN 1 
	SELECT ID , TIPO FROM ANIMALES 
	WHERE ID = 1;
-- SELECCIONO EL ID Y EL TIPO DE LA TABLA ANIMALES, UNICAMENTE DONDE LOS VALORES DE ID SEAN 1 Y SEAN UN 'CHANCHITO' 

SELECT ID , TIPO FROM ANIMALES 
	WHERE ID = 1 AND TIPO = 'CHANCHITO';

-- MODIFICO PUERQUITO PARA QUE SEA CHANCHITO EN EL ID 1 
UPDATE animales SET TIPO = 'CHANCHITO'
WHERE ID = 1 ;

-- ELIMINO LOS REGITROS DONDE SEA ESTADO 'FELIZ' Y EL ID SEA 3 
DELETE FROM animales WHERE ESTADO = 'FELIZ';

DELETE FROM ANIMALES WHERE ID = 3 ;


-- ELIMINO LOS MISMOS REGISTROS PERO USANDO OR PARA CONCATENAR QUEDANDO LA TABLA VACIA 
DELETE FROM animales WHERE ESTADO = 'FELIZ' OR ID =3;
