create procedure SP_PRUEBA

AS

DECLARE @CAMPO AS VARCHAR(20)

BEGIN 

       IF EXISTS (
       SELECT 1 FROM CARRERAS WHERE nombre = @CAMPO )

	 --  SET @CAMPO = (SELECT NOMBRE FROM CARRERAS WHERE  nombre = @CAMPO  )

	   PRINT 'SI SE ENCUENTRA EL NOMBRE INDICADO:' 

	   ELSE

	 --  BEGIN
	         PRINT 'NO SE ENCUENTRA EL NOMBRE INDICADO'
	 --  END


END

--SE EJECUTA EL PA
exec SP_PRUEBA  'HOLA '

