
select COD_PRO,DES_PRO
/*UPDATE  BOL_Migración_BienesDeUso_1 SET
DES_PRO = (CASE WHEN COD_PRO=130 THEN 'PAPAS FRITAS' 
                WHEN COD_PRO=1696 THEN 'DINOSAURIO'
				WHEN COD_PRO=1708 THEN 'PUERQUITO'
				WHEN COD_PRO = 1767 THEN 'CARPA'
				WHEN COD_PRO = 2013 THEN 'CALABAZA'
				WHEN COD_PRO = 2058 THEN 'CHANCHITO FELIZ'
				WHEN COD_PRO = 2121 THEN 'PANCHITO'
				WHEN COD_PRO = 2484 THEN 'PAPANATAS'
				WHEN COD_PRO = 2503 THEN 'PALTA'
				WHEN COD_PRO = 2584 THEN 'AZUCAR'
				WHEN COD_PRO = 2610 THEN 'YOUGURT'
				WHEN COD_PRO = 2614 THEN 'ALI'
				WHEN COD_PRO = 2615 THEN 'ORI'
				WHEN COD_PRO = 357 THEN 'JAMAICA' ELSE '' END) */
from BOL_Migración_BienesDeUso_1
where cod_pro not in (select COD_PRO from PR_JU..PROD_SER)
GROUP BY  COD_PRO,DES_PRO


--TAREA ACOMODAR LAS FEC_AFECTA Q SEAN SDATE = FALSE

