CREATE TABLE CLIENTES (
    ID_Cliente INT PRIMARY KEY,
    Apellido NVARCHAR(255),
    Nombre NVARCHAR(255),
    Dirección NVARCHAR(255),
    DNI NVARCHAR(20),
    Fecha_Nac DATE,
    ID_Localidad INT,
--    FOREIGN KEY (ID_Localidad) REFERENCES LOCALIDAD(ID_Localidad)
);

-- Crear la tabla AUTOMOVIL
CREATE TABLE AUTOMOVIL (
    ID_Automovil INT PRIMARY KEY,
    Marca NVARCHAR(255),
    Modelo NVARCHAR(255),
    Año_Fabricación INT,
    Año_Ingreso INT
);

-- Crear la tabla ALQUILER
CREATE TABLE ALQUILER (
    ID_Alquiler INT PRIMARY KEY,
    ID_Automovil INT,
    ID_Cliente INT,
    Km_Inicial INT,
    KM_Final INT,
    ID_Localidad_Inicial INT,
    Precio_alquiler DECIMAL(10, 2),
    ID_Empleado INT,
    FOREIGN KEY (ID_Automovil) REFERENCES AUTOMOVIL(ID_Automovil),
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTES(ID_Cliente),
   -- FOREIGN KEY (ID_Localidad_Inicial) REFERENCES LOCALIDAD(ID_Localidad),
 --   FOREIGN KEY (ID_Empleado) REFERENCES EMPLEADOS(ID_Empleado)
);

-- Crear la tabla LOCALIDAD
CREATE TABLE LOCALIDAD (
    ID_Localidad INT PRIMARY KEY,
    Ciudad NVARCHAR(255),
    Dirección NVARCHAR(255),
    Telefono NVARCHAR(20),
    ID_Gerente INT,
  --  FOREIGN KEY (ID_Gerente) REFERENCES EMPLEADOS(ID_Empleado)
);

-- Crear la tabla EMPLEADOS
CREATE TABLE EMPLEADOS (
    ID_Empleado INT PRIMARY KEY,
    Nombre NVARCHAR(255),
    Apellido NVARCHAR(255),
    Fecha_Contratación DATE,
    Salario DECIMAL(10, 2),
    ID_Localidad INT,
    Comisión DECIMAL(5, 2),
    FOREIGN KEY (ID_Localidad) REFERENCES LOCALIDAD(ID_Localidad)
);



ALTER TABLE CLIENTES 
ADD CONSTRAINT FK_CLIENTES_LOCALIDAD
FOREIGN KEY (ID_Localidad) 
REFERENCES LOCALIDAD(ID_Localidad);

ALTER TABLE ALQUILER
ADD CONSTRAINT FK_ALQUILER_LOCALIDAD
FOREIGN KEY (ID_Localidad_Inicial)
REFERENCES LOCALIDAD(ID_Localidad)

ALTER TABLE ALQUILER 
ADD CONSTRAINT FK_ALQUILER_EMPLEADOS
FOREIGN KEY (ID_Empleado)
REFERENCES EMPLEADOS(ID_Empleado)



ALTER TABLE LOCALIDAD 
ADD CONSTRAINT FK_LOCALIDAD_EMPLEADOS
FOREIGN KEY (ID_Gerente)
REFERENCES EMPLEADOS(ID_Empleado)



-- 5)
SELECT * FROM EMPLEADOS
WHERE DATEDIFF(YEAR, Fecha_Contratación, GETDATE()) > 10;


--!)




