CREATE DATABASE USUARIOS 

USE  USUARIOS

CREATE TABLE USUARIO (
	ID INT,
	NOMBRE VARCHAR(255),
	APELLIDO VARCHAR(255),
	MAIL VARCHAR(255),
	CALLE VARCHAR(255),
	ALTURA INT,

	PRIMARY KEY ( ID)
)


INSERT INTO USUARIO ( NOMBRE , APELLIDO, MAIL, CALLE, ALTURA) 
	VALUES ('FRANCO', 'FURLANI', ' FRANCOFURLANI@GMAIL.COM', 'BENJAMIN GOULD',684),
			('STEFANIA' , 'ARRUK' , 'STEFANIAARRUK@GMAIL.COM', 'ARGANDOÑA', 1411),
			('JULEITA' , 'RUIZ', 'JULIETRUIZ@GMAIL.COM', 'ESPORA', 790),
			('PACO', 'SALSEDO', 'PACOSALSEDO@GMAIL.COM', 'BRUNO GENTA' , 1400)


 
 CREATE TABLE TURNO_MEDICO ( 
    ID_TURNO INT PRIMARY KEY,
    NUMERO_TURNO INT,
    ID_USUARIO INT,
    DIA DATE,
    MOTIVO VARCHAR(100),
    DIAGNOSTICO VARCHAR(200),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
)
 
